defaults:
  - ../../models/image_encoder@model.image_encoder: minicpm_v_4_6_vit
  - ../../models/image_projector@model.image_projector: minicpm_v_4_6_merger
  - ../../models/minicpm_v_4_6@model.foundation: minicpm_v_4_6_llm
  - _self_

model:
  model_type: minicpm_v_4_6
  position_idx_func: ${position_func:rope_ids_qwen3vl}
  loss_func: ${loss_func:default}
  mix_used_vision_encoder: true
  mix_used_vision_projector: true
  foundation:
    model_spec: ["loongforge.models.language.qwen3_5.qwen3_5_layer_spec", "get_qwen3_5_transformer_layer_spec"]
  image_encoder:
    model_spec: null
  image_projector:
    model_spec: null
