# qwen3 model configuration
_target_: loongforge.models.language.Qwen3Config
num_layers: 62
hidden_size: 6144
ffn_hidden_size: 8192
num_attention_heads: 96
vocab_size_in_config_file: 151936
make_vocab_size_divisible_by: 128

group_query_attention: true
num_query_groups: 8
position_embedding_type: "rope"
add_position_embedding: false
rotary_interleaved: false
normalization: "RMSNorm"
swiglu: true
attention_dropout: 0
hidden_dropout: 0
add_bias_linear: false
add_qkv_bias: false
qk_layernorm: true
untie_embeddings_and_output_weights: true
kv_channels: 128
num_experts: 160
moe_ffn_hidden_size: 2560
rotary_emb_func: "RotaryEmbedding"
rotary_base: 1000000
model_type: "qwen"
convert_file: ${oc.env:LOONGFORGE_PATH}/configs/models/qwen3/ckpt_convert/qwen3_moe_convert.yaml
# variable_seq_lengths: true
