# qwen3 model configuration
_target_: loongforge.models.language.Qwen3Config

num_layers: 48
hidden_size: 2048
ffn_hidden_size: 6144
num_attention_heads: 32
vocab_size_in_config_file: 151936
make_vocab_size_divisible_by: 128

group_query_attention: true
num_query_groups: 4
position_embedding_type: "rope"
add_position_embedding: false
rotary_interleaved: false
normalization: "RMSNorm"
swiglu: true
attention_dropout: 0.0
hidden_dropout: 0.0
add_bias_linear: false
add_qkv_bias: false
qk_layernorm: true
untie_embeddings_and_output_weights: true
kv_channels: 128
num_experts: 128
moe_ffn_hidden_size: 768
rotary_emb_func: "RotaryEmbedding"
model_type: "qwen"

convert_file: ${oc.env:LOONGFORGE_PATH}/configs/models/qwen3/ckpt_convert/qwen3_moe_convert.yaml
# variable_seq_lengths: true