# deepseek_v2_lite model config
_target_: loongforge.models.language.DeepseekConfig

num_layers: 27
hidden_size: 2048
ffn_hidden_size: 10944
num_attention_heads: 16
num_experts: 64
moe_ffn_hidden_size: 1408
moe_shared_expert_intermediate_size: 2816
q_lora_rank: null
kv_lora_rank: 512
qk_head_dim: 128
qk_pos_emb_head_dim: 64
v_head_dim: 128
moe_layer_freq: ${moe_freq:"[0]*1+[1]*26"}

# common default
position_embedding_type: "rope"
add_position_embedding: false
rotary_interleaved: false
normalization: "RMSNorm"
swiglu: true
attention_dropout: 0
hidden_dropout: 0
add_bias_linear: false
add_qkv_bias: false
qk_layernorm: true
untie_embeddings_and_output_weights: true
vocab_size_in_config_file: 102400
num_query_groups: 16
apply_rope_fusion: true
multi_latent_attention: true
model_type: "deepseek"

convert_file: ${oc.env:LOONGFORGE_PATH}/configs/models/deepseek_v2/ckpt_convert/deepseek_v2_lite_convert.yaml