
_target_: loongforge.models.vision.InternMLPAdapterConfig

normalization: LayerNorm
model_type: "intern_adapter"
layernorm_epsilon: 1e-5

convert_file: ${oc.env:LOONGFORGE_PATH}/configs/models/image_projector/ckpt_convert/intern_mlp_adapter_convert.yaml