
_target_: loongforge.models.vision.MLPAdapterConfig

normalization: "RMSNorm"
add_bias_linear: True
model_type: "qwen2_5_vl_adapter"

convert_file: ${oc.env:LOONGFORGE_PATH}/configs/models/image_projector/ckpt_convert/qwen_mlp_adapter_convert.yaml