# llama3_8b model config
_target_: loongforge.models.language.LLaMAConfig

num_layers: 32
hidden_size: 4096
ffn_hidden_size: 14336
num_attention_heads: 32

# common default
group_query_attention: true
num_query_groups: 8
position_embedding_type: "rope"
add_position_embedding: false
rotary_interleaved: false
normalization: "RMSNorm"
swiglu: true
attention_dropout: 0
hidden_dropout: 0
add_bias_linear: false
add_qkv_bias: false
qk_layernorm: false
untie_embeddings_and_output_weights: true
model_type: "llama"

convert_file: ${oc.env:LOONGFORGE_PATH}/configs/models/llama3/ckpt_convert/llama3_convert.yaml