# deepseek_v3 model config
_target_: loongforge.models.language.DeepseekConfig

num_layers: 61
hidden_size: 7168
ffn_hidden_size: 18432
num_attention_heads: 128
num_query_groups: 128
num_experts: 256
mtp_num_layers: 1
moe_ffn_hidden_size: 2048
moe_shared_expert_intermediate_size: 2048
q_lora_rank: 1536
kv_lora_rank: 512
qk_head_dim: 128
qk_pos_emb_head_dim: 64
v_head_dim: 128
moe_layer_freq: ${moe_freq:"[0]*3+[1]*58"}
qk_layernorm: true
vocab_size_in_config_file: 129280

# Deepseek Sparse Attention
experimental_attention_variant: "dsa"
dsa_indexer_n_heads: 64
dsa_indexer_head_dim: 128
dsa_indexer_topk: 2048
dsa_indexer_loss_coeff: 1.0
dsa_indexer_use_sparse_loss: true

# common default
position_embedding_type: "rope"
add_position_embedding: false
rotary_interleaved: false
normalization: "RMSNorm"
swiglu: true
attention_dropout: 0
hidden_dropout: 0
add_bias_linear: false
add_qkv_bias: false
untie_embeddings_and_output_weights: true
apply_rope_fusion: false  # no support rope fusion yet
multi_latent_attention: true
model_type: "deepseek"

convert_file: ${oc.env:LOONGFORGE_PATH}/configs/models/deepseek_v3/ckpt_convert/deepseek_v3_2_convert.yaml