# hydra:
#   searchpath:
#     - file://configs/

defaults:
  - ../../models/image_encoder@model.image_encoder: qwen3_5_vit
  - ../../models/image_projector@model.image_projector: qwen_mlp_adapter
  - ../../models/qwen3.6@model.foundation: qwen3_6_27b_llm
  - _self_

model:
  model_type: qwen3_5
  position_idx_func: ${position_func:rope_ids_qwen3vl}
  loss_func: ${loss_func:default}
  foundation:
    rotary_emb_func: "Qwen35RotaryEmbedding"
    rotary_base: 10000000
    mrope_section: [11, 11, 10]
    rotary_interleaved: False
    model_spec: ["loongforge.models.language.qwen3_5.qwen3_5_layer_spec", "get_qwen3_5_transformer_layer_spec"]
  image_encoder:
    model_spec: ["loongforge.models.vision.qwen3_5.qwen3_5_vision_layer_spec",
                 "get_qwen3_5_vision_model_layer_with_te_spec"]
  image_projector:
    activation_func: ${act:gelu}
    normalization: "LayerNorm"
    convert_file: ${oc.env:LOONGFORGE_PATH}/configs/models/image_projector/ckpt_convert/qwen_3_mlp_adapter_convert.yaml
    bias_activation_fusion: False
    gated_linear_unit: False
    model_spec: ["loongforge.models.vision.qwen3_5.qwen3_5_vision_layer_spec",
                 "get_adapeter_layer_with_te_spec"]
