
_target_: loongforge.models.vision.Qwen2VisionModelConfig

num_layers: 32
hidden_size: 1280
kv_channels: 80
ffn_hidden_size: 5120
patch_size: 14
num_attention_heads: 16
num_query_groups: 16
image_size: [1344, 1344]
activation_func: ${act:gelu}
add_bias_linear: false
add_qkv_bias: false
swiglu: false
gated_linear_unit: false
position_embedding_type: "none"
bias_activation_fusion: false
hidden_dropout: 0.0
attention_dropout: 0.0
normalization: "LayerNorm"
apply_rope_fusion: true

model_type: "qwen2_vit"
convert_file: ${oc.env:LOONGFORGE_PATH}/configs/models/image_encoder/ckpt_convert/qwen2_5_vit_convert.yaml
