hydra:
  searchpath:
    - file://${oc.env:LOONGFORGE_PATH}/configs/models/

defaults:
  - deepseek3@module: ???
  - _self_


args:
  common:
    num_layers: ${module.num_layers}
    hidden_size: ${module.hidden_size}
    ffn_hidden_size: ${module.ffn_hidden_size}
    num_attention_heads: ${module.num_attention_heads}
    num_key_value_heads: ${module.num_query_groups}
    vocab_size: ${module.vocab_size_in_config_file}
    num_experts: ${module.num_experts}
    mtp_num_layers: ${module.mtp_num_layers}

  huggingface:
    mtp_layer_id: 61
  mcore:
    untie_embeddings_and_output_weights: true
    add_embedding_padding: true
    transpose_mlp_dense: true
    transpose_query_key_value: true
name_map:
  huggingface:
    word_embeddings: model.embed_tokens
    transformer: model
    layer_prefix: layers
    input_layernorm: input_layernorm
    attention.q_down: self_attn.q_a_proj
    attention.q_up: self_attn.q_b_proj
    attention.q_up_layernorm: self_attn.q_a_layernorm
    attention.kv_down: self_attn.kv_a_proj_with_mqa
    attention.kv_up: self_attn.kv_b_proj
    attention.kv_up_layernorm: self_attn.kv_a_layernorm
    attention.indexer.k_norm: self_attn.indexer.k_norm
    attention.indexer.weights_proj: self_attn.indexer.weights_proj
    attention.indexer.wk: self_attn.indexer.wk
    attention.indexer.wq_b: self_attn.indexer.wq_b
    attention.dense: self_attn.o_proj
    post_attention_layernorm: post_attention_layernorm
    moe.gate: mlp.gate
    moe.gate.bias: mlp.gate.e_score_correction_bias
    moe.expert: mlp.experts
    moe.shared_expert: mlp.shared_experts
    moe.expert_h_to_4h:
    - gate_proj
    - up_proj
    mlp.dense_h_to_4h:
    - mlp.gate_proj
    - mlp.up_proj
    moe.expert_4h_to_h: down_proj
    mlp.dense_4h_to_h: mlp.down_proj
    final_layernorm: model.norm
    word_embeddings_for_head: lm_head
    mtp_word_embeddings: embed_tokens
    mtp_enorm: enorm
    mtp_hnorm: hnorm
    mtp_eh_proj:
      name: eh_proj
      dtype: bf16
    mtp_shared_head_norm: shared_head.norm
    mtp_shared_head_head: shared_head.head
  mcore:
    word_embeddings: embedding.word_embeddings
    word_position_embeddings: model.embedding.position_embeddings
    transformer: model
    layer_prefix: decoder.layers
    mtp_layer_prefix: mtp.layers
    input_layernorm: input_layernorm
    attention.q_down:
      name: self_attention.linear_q_down_proj
      extra: true
      fp8: true
      fp8_ignore_tp: true
    attention.q_up:
      name: self_attention.linear_q_up_proj
      extra: true
      fp8: true
    attention.q_up_layernorm:
      name: self_attention.q_layernorm
      extra: true
    attention.kv_down:
      name: self_attention.linear_kv_down_proj
      extra: true
      fp8: true
      fp8_ignore_tp: true
    attention.kv_up:
      name: self_attention.linear_kv_up_proj
      extra: true
      fp8: true
    attention.kv_up_layernorm:
      name: self_attention.kv_layernorm
      extra: true
    attention.indexer.k_norm:
      name: self_attention.core_attention.indexer.k_norm
      extra: true
    attention.indexer.weights_proj:
      name: self_attention.core_attention.indexer.linear_weights_proj
      extra: true
    attention.indexer.wk:
      name: self_attention.core_attention.indexer.linear_wk
      fp8: true
      extra: true
    attention.indexer.wq_b:
      name: self_attention.core_attention.indexer.linear_wq_b
      fp8: true
      extra: true
    attention.dense:
      name: self_attention.linear_proj
      fp8: true
      extra: true
    post_attention_layernorm: pre_mlp_layernorm
    moe.gate: mlp.router
    moe.gate.bias: mlp.router.expert_bias
    moe.expert: mlp.experts.local_experts
    moe.groupedgemm.expert: mlp.experts
    moe.shared_expert: mlp.shared_experts
    moe.expert_h_to_4h:
      name: linear_fc1
      fp8: true
      extra: true
    mlp.dense_h_to_4h:
      name: mlp.linear_fc1
      fp8: true
      extra: true
    moe.expert_4h_to_h:
      name: linear_fc2
      fp8: true
      extra: true
    mlp.dense_4h_to_h:
      name: mlp.linear_fc2
      fp8: true
      extra: true
    final_layernorm:
      name: decoder.final_layernorm
      extra: true
    word_embeddings_for_head: output_layer
    transformer_tpl: model%d
    mtp_word_embeddings: embedding.word_embeddings
    mtp_enorm: enorm
    mtp_hnorm: hnorm
    mtp_eh_proj:
      name: eh_proj
      dtype: fp8
    mtp_shared_head_norm:
      name: final_layernorm
      extra: true
    mtp_shared_head_head: output_head
    mtp_name_prefix_for_layer: transformer_layer
torch_dtype: bfloat16
